# CocoaMySQL dump
# Version 0.7b5
# http://cocoamysql.sourceforge.net
#
# Host: localhost (MySQL 5.0.45)
# Database: shaadigiftlist_development
# Generation Time: 2008-05-07 22:53:08 +0100
# ************************************************************

# Dump of table products
# ------------------------------------------------------------

INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('1','/images/products/no_image.gif','Electronics','???','Russell Hobbs Montana Gift Pack','Kettle:\n3kW rapid boil concealed element for easy cleaning and to reduce limescale build up.\n1.7 litre capacity.\nAnti-scale washable filter.\nWater gauge.\nSoft touch handle.\nIlluminated power indicator.\nMulti-directional 360 degree base with cord storage. \n2 slice toaster:\nWide/long slots for bigger cuts of bread.\nHigh-lift facility.\n6 position variable browning control. \nFrozen bread and cancel functions.\nRemovable crumb tray.\nPolished stainless steel finish. ','34392E3939','32302E3030','31302E3030','35392E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('2','/images/products/no_image.gif','Electronics','???','Breville Stainless Steel and Cream Gift Pack','3kW.\n1.7 litre capacity. \nDry boil protection. \nSafety cut out. \nRemovable, washable limescale filter. \nWater window.\nSpout fill. \nAutomatic switch off. \nNeon power indicator. \n360 degree base. \nNon slip feet. \nCord storage. \n2 Slice Toaster:\nVariable width. \nSelf centring. \nVariable browning control. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage. ','34392E3939','32302E3030','31302E3030','35392E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('3','/images/products/no_image.gif','Electronics','???','Breville Silver Triple Pack','3kW fastboil. \n1.7 litre capacity jug kettle. \nToaster: \n2 slice cool wall toaster. \nVariable width toasting slots. \nHigh lift. \nMid cycle cancel facility. \nSandwich toaster: \n2 slice sandwich toaster with non-stick plates.\nPower on and ready to cook indicators.\nStylish stainless steel and silver finish to all products. ','34392E3939','32352E3030','31322E3530','36322E3439',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('4','/images/products/DelonghiCrema4SliceToaster.jpg','Electronics','???','DeLonghi Crema 4 Slice Toaster','Cream. \nRetro style. \nCan operate 2 slots independently. \nVariable width. \nSelf centring. \nVariable browning control. \nHi-rise facility. \nCancel/frozen/reheat/stop facility. \n2 slide out crumb trays.\nNon slip feet.\nCord storage.\n','33392E3939','352E3030','322E3030','34312E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('5','/images/products/RussellHobbsClassic4SliceToaster.jpg','Electronics','???',' Russell Hobbs Classic 4 Slice Toaster','Independent 2 slice operation. \nVariable width. \nSelf centring. \nCoolwall. \nVariable browning control. \nHi-lift. \nCancel/frozen/reheat facility. \n2 removable crumb trays. \nNon slip feet.\n','33342E3939','31302E3030','332E3530','33382E3439',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('6','/images/products/Deco2SliceBrushedStainlessSteelToaster.jpg','Electronics','???',' Deco 2 Slice Brushed Stainless Steel Toaster','Polished stainless steel finish.\nEnergy saving independent 2 slice operation.\nWide/long slots for bigger cuts of bread.\n6 position variable browning control.\nHigh lift facility.\nFrozen bread and cancel functions. \nPolished stainless steel finish.\nRemovable crumb tray. \n','33342E3934','31302E3030','332E3439','33382E3433',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('7','/images/products/BrevilleStainlessSteel4SliceToaster.jpg','Electronics','???',' Breville Stainless Steel 4 Slice Toaster','Independent 2 slice operation. \nDigital display and LED indicator lights to indicate where the toasting cycle is up to. \nVariable width. \nSelf centring. \nCoolwall. \nElectronic variable browning control. \nHigh lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray.\n','32392E3939','31302E3030','332E3030','33322E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('8','/images/products/RussellHobbsRetro 2SliceStainlessSteelToaster.jpg','Electronics','???','Russell Hobbs Retro 2 Slice Stainless Steel Toaster','Variable width. \nSelf centring. \nVariable browning control. \nHi lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage. \n','32392E3939','31302E3030','332E3030','33322E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('9','/images/products/TefalAvantiBlackandSilver4SliceToaster.jpg','Electronics','???',' Tefal Avanti Black and Silver 4 Slice Toaster','Front angled toaster for safe viewing whilst toasting. \nIndependent 2 slice operation. \nExtra deep variable width bread slots. \nSelf centring. \nCoolwall. \nVariable browning control. \nHi-lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage. \n','32392E3939','31302E3030','332E3030','33322E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('10','/images/products/MorphyRichardsGraphiteComplements4SliceToaster.jpg','Electronics','???',' Morphy Richards Graphite Complements 4 Slice Toaster','Independent 2 slice operation. \nElectronic variable browning control. \nCool touch. \nCountdown feature. \nHi lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nCord storage.\n','32392E3939','31302E3030','332E3030','33322E3939',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('11','/images/products/BrevilleCafeStyleSandwichPressandMelt.jpg','Electronics','???',' Breville Cafe Style Sandwich Press and Melt','Makes 2 rounds of sandwiches. \nCafe style toasted panini and ciabatta snacks in minutes. \n2000 watts for rapid heat up. \nNon-stick flat cooking plates. \nUnique floating hinge top plate. \nAdjustable top plate - suitable for melting cheese. \nPower on/ready lights. \nUpright storage facilities\n','32392E3937','352E3030','312E3530','33312E3437',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('12','/images/products/MorphyRichards44065AccentsPowder Pink2SliceToaster.jpg','Electronics','???',' Morphy Richards 44065 Accents Powder Pink 2 Slice Toaster','Variable bread width. \nDeep toasting chamber for large items. \nHi-lift. \nCancel/frozen/reheat facility. \nRemovable crumb tray. \nNon slip feet. \nCord storage. \n','32392E3935','352E3030','312E3530','33312E3435',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('13','/images/products/MorphyRichardsAccentsJetBlack2SliceToaster.jpg','Electronics','???',' Morphy Richards Accents Jet Black 2 Slice Toaster','Variable bread width. \nDeep toasting chamber for large items. \nVariable browning control. \nHi-lift facility for removing small items. \nCancel/frozen/reheat facility. \nRemovable washable crumb tray. \nNon slip feet. \nCord storage.\n','32392E3739','352E3030','312E3439','33312E3238',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('14','/images/products/MorphyRichards447093in1SnackingMachine.jpg','Electronics','???',' Morphy Richards 44709 3 in 1 Snacking Machine','740 watts.\n2 deep fill sandwich plates. \n2 health grill plates for cooking meat, vegetables and fish. \nNon stick, easy clean removable plates. \nMakes 2 rounds of filled toasted sandwiches. \nCarry handle incorporating locking clasp. \nSuitable for upright storage\n\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('15','/images/products/BrevilleSilverStyle4SliceIlluminatedToaster.jpg','Electronics','???',' Breville Silver Style 4 Slice Illuminated Toaster','Illuminating toasting status indicator lights. \nVariable width. \nSelf centring. \nCoolwall. \nVariable browning control. \nHi lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage. \n','32372E3939','352E3030','312E3430','32392E3339',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('16','/images/products/CookworksSignaturePaniniPress.jpg','Electronics','???',' Cookworks Signature Panini Press','Makes caf? style toasted ciabatta and panini bread sandwiches.  \nHorizontal floating hinge for variable thickness sandwiches.  \nNon-stick coating.  \nPower on and ready indicator.  \nStands up for easy storage. \nCord storage. \n','32362E3939','352E3030','312E3335','32382E3334',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('17','/images/products/Disney2SliceToaster.jpg','Electronics','???',' Disney 2 Slice Toaster','Toasts Mickey Mouse\'s face onto each slice. \nPlays the Mickey Mouse March music when toast is ready. \nVariable browning control. \nCancel function. \nRemovable crumb tray. \nNon slip feet. \nIncludes quick start guide\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('18','/images/products/no_image.gif','Electronics','???',' Prestige Insignia 2 Slice Brushed Stainless Steel Toaster','2 deep variable width toasting slots for thick and thin bread. \nAuto pop up. \n5 position electronic variable browning control with LED indicator. \nHigh-lift facility for easy removal small items. \nDefrost and mid cycle cancel button with illumination. \nEasy removable crumb tray. \nNon-slip feet. \n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('19','/images/products/RussellHobbsRetro4SliceStainlessSteelToaster.jpg','Electronics','???',' Russell Hobbs Retro 4 Slice Stainless Steel Toaster','Independent 2 slice operation. \nVariable width. \nSelf centring. \nVariable browning control. \nHi lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('20','/images/products/Breville4SliceSilverSandwichToaster.jpg','Electronics','???','Breville 4 Slice Silver Sandwich Toaster','4 deep fill plates make a fulfilling snack.\nCuts and seals to reduce leakage.\nEasy clean, non stick plates.\nRapid heat-up and high temperature makes golden brown sandwiches.\nPower on and ready to cook indicators.\nVertical storage and cord wrap to save on space.\nNon slip feet for safety. \nContemporary satin silver finish. \n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('21','/images/products/no_image.gif','Electronics','???',' Kenwood Miro Pink 2 Slice Toaster','Wide self centring deep slots. \nVariable browning control. \nHi lift. \nIlluminated control panel for cancel/defrost/reheat facility. \nSlide out crumb tray. \nCord storage\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('22','/images/products/MorphyRichards44407Style4SliceToaster.jpg','Electronics','???',' Morphy Richards 44407 Style 4 Slice Toaster','Deep variable width toasting chamber. \nVariable browning control. \nHi-lift. \nCancel/frozen/reheat facility. \nBun warming rack. \nRemovable crumb tray. \nNon slip feet. \nCord storage\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('23','/images/products/CookworksSignature4SliceStainlessSteelToaster.jpg','Electronics','???',' Cookworks Signature 4 Slice Stainless Steel Toaster','Independent 2 slice operation. \nVariable width. \nSelf centring. \nVariable browning control. \nHi lift. \nCancel/frozen/reheat facility. \nMid cycle cancel. \nRemovable crumb tray. \nNon slip feet. \nCord storage. \n\n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);
INSERT INTO `products` (`id`,`image_url`,`category`,`reference`,`name`,`description`,`unit_cost`,`markup_percentage`,`markup_amount`,`price`,`created_at`,`updated_at`) VALUES ('24','/images/products/no_image.gif','Electronics','???',' Tefal Toast and Grill','1300 watts. \nCompact size (no bigger than an average 4 slice toaster). \n2 trays (toast/grill rack and enamel plate). \nBooster button to toast or reheat in ultra fast time (cooks chilled Pizza in 5 minutes - 3 x faster than a conventional oven). \nPerfect toasting control thanks to two heating elements (top and below). \nElectronic 25 minute timer with variable browning control. \nOn/off indicator. \nEasy to clean thanks to its hinged grill. \nNon slip feet. \n','32342E3939','352E3030','312E3235','32362E3234',NULL,NULL);


